### ISSUE TITLE
创建菜单发生错误！

### ISSUE THREAD

**Issue by jaiiye** [chanjarster/weixin-java-tools#111]
InputStream inputStream = getClass().getResourceAsStream("/menus.json");
WxMenu wxMenu = WxMenu.fromJson(inputStream);
wxMpService.menuCreate(wxMenu);

menus.json数据来自微信公众平台开发者文档[click和view的请求示例]
http://mp.weixin.qq.com/wiki/13/43de8269be54a0a6f64413e4dfa94f39.html

**Comment by chanjarster** [comment]
看[WxMenuGsonAdapter.java#L60](https://github.com/chanjarster/weixin-java-tools/blob/c23293f83ae76bc352baa5a6e09f1db20e3b7bdf/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/json/WxMenuGsonAdapter.java#L60)，因为微信的菜单查询和菜单创建的json不一样，所以用这个GsonAdapter反序列化出来一个java对象是不对的，然后你拿了不对的WxMenu对象去创建菜单自然不行了。

你应该自己在程序里构建WxMenu，这样就会成功了。

**Comment by jaiiye** [comment]
嗯，看了下，是这样的，感觉有点扯蛋。不过在程序里构建WxMenu，感觉工作量有点大 ，失掉了本来的精简！

**Comment by jaiiye** [comment]
提供一个原生json创建菜单的接口吧；又或者我们可以把创建、查询实体分开，这样也不容易让人误解。

**Comment by wintersun** [comment]
提供原生json接口的建议挺好，更为直观和易于维护，请考虑！
如有可能，我愿意先做尝试，再pull request。

**Comment by chanjarster** [comment]
按照这样构建不就行了么 ``{ menu : { button : ... } }``,

原生json接口是个什么意思？

创建、查询实体分开才失掉本来的精简。

**Comment by wintersun** [comment]
Sorry，之前我表述不清楚，我的建议是类似这样：
menuCreate(String jsonFile)  //菜单的定义直接在json文件中更直观和易于维护！

**Comment by chanjarster** [comment]
> 菜单的定义直接在json文件中更直观和易于维护

还是无法理解

他这样不行么？

```java
InputStream inputStream = getClass().getResourceAsStream("/menus.json");
WxMenu wxMenu = WxMenu.fromJson(inputStream);
```

menus.json的格式改成这样``{ menu : { button : ... } }``就行了呀。

**Comment by jaiiye** [comment]
我们的意思是wxMpService.menuCreate(String jsonMenus)这样直接创建！
jsonMenus就是微信官网那种json格式字串，失掉了本来的精简就是相对于我们在程序中手动创建WxMenu实体来说的。
至于创建、查询实体分开这种方式，主要也是为了解决方便创建菜单，可能是我自己陷入了WxMenu.fromJson这个方法，想着分开就不会有这种冲突！

**Comment by jaiiye** [comment]
嗯，我前面好像也改过menus.json格式，可能没改对，我再试试。

**Comment by jaiiye** [comment]
我又试了试，格式改成这样 { menu : { button : ... } }确实还是不行。

**Comment by chanjarster** [comment]
那我瞅瞅。

**Comment by chanjarster** [comment]
我在WxMenu和WxMenuButton上加了toString方法，然后用下面的代码测试，是成功的，json采用的是这个网址 http://mp.weixin.qq.com/wiki/16/ff9b7b85220e1396ffa16794a9d95adc.html

```java
  public static void main(String[] args) {
    String i = "{\"menu\":{\"button\":[{\"type\":\"click\",\"name\":\"今日歌曲\",\"key\":\"V1001_TODAY_MUSIC\",\"sub_button\":[]},{\"type\":\"click\",\"name\":\"歌手简介\",\"key\":\"V1001_TODAY_SINGER\",\"sub_button\":[]},{\"name\":\"菜单\",\"sub_button\":[{\"type\":\"view\",\"name\":\"搜索\",\"url\":\"http://www.soso.com/\",\"sub_button\":[]},{\"type\":\"view\",\"name\":\"视频\",\"url\":\"http://v.qq.com/\",\"sub_button\":[]},{\"type\":\"click\",\"name\":\"赞一下我们\",\"key\":\"V1001_GOOD\",\"sub_button\":[]}]}]}}";
    WxMenu wxMenu = WxMenu.fromJson(i);
    System.out.println(wxMenu);
    System.out.println(wxMenu.toJson());
  }
```

请确定你的其他的配置没有问题吗？

**Comment by jaiiye** [comment]
嗯，前面WxMenu.fromJson出错就是因为JSON中的sub_button字段，你这个是用的查询JSON（微信服务器返回给我们的），它只查了一级菜单，现在你反序列化的时候没有二级菜单，所以不会有错。查询、创建本就不同，这也是我前面说把创建、查询实体分开的一个原因。
这个创建菜单，你就拿创建菜单示例中的数据么，你那看异常日志更清晰。见http://mp.weixin.qq.com/wiki/13/43de8269be54a0a6f64413e4dfa94f39.html

**Comment by jaiiye** [comment]
其实把查询、创建实体分开确实可能更绕，像是为了面向对象而面向对象。
还是前面说得 直接提供一个类似 wxMpService.menuCreate(jsonMenus) 这样的方法最简洁。
WxMenu 中一些方法整理一下，将它仅做为查询菜单使用，这样是不是更好？

**Comment by chanjarster** [comment]
菜单查询API文档提供的数据是这样的：

```javascript
{
     "button":[
     {	
          "type":"click",
          "name":"今日歌曲",
          "key":"V1001_TODAY_MUSIC"
     },
     {
          "name":"菜单",
          "sub_button":[
          {	
              "type":"view",
              "name":"搜索",
              "url":"http://www.soso.com/"
          },
          {
             "type":"view",
             "name":"视频",
             "url":"http://v.qq.com/"
          },
          {
             "type":"click",
             "name":"赞一下我们",
             "key":"V1001_GOOD"
          }]
     }]
 }
```

菜单创建API文档提供的数据是这样的：

```javascript
{
  "menu": {
    "button": [
      {
        "type": "click",
        "name": "今日歌曲",
        "key": "V1001_TODAY_MUSIC",
        "sub_button": []
      },
      {
        "type": "click",
        "name": "歌手简介",
        "key": "V1001_TODAY_SINGER",
        "sub_button": []
      },
      {
        "name": "菜单",
        "sub_button": [
          {
            "type": "view",
            "name": "搜索",
            "url": "http://www.soso.com/",
            "sub_button": []
          },
          {
            "type": "view",
            "name": "视频",
            "url": "http://v.qq.com/",
            "sub_button": []
          },
          {
            "type": "click",
            "name": "赞一下我们",
            "key": "V1001_GOOD",
            "sub_button": []
          }
        ]
      }
    ]
  }
}
```

可以看出这两个的区别是 创建API 比 查询API 多套了一层 ``menu``。

我用创建API的json反序列化，成功

```java
WxMenu menu = WxMenu.fromJson(字符串);
System.out.println(menu);
```

```
WxMenu{buttons=[WxMenuButton{type='click', name='今日歌曲', key='V1001_TODAY_MUSIC', url='null', subButtons=[]}, WxMenuButton{type='click', name='歌手简介', key='V1001_TODAY_SINGER', url='null', subButtons=[]}, WxMenuButton{type='null', name='菜单', key='null', url='null', subButtons=[WxMenuButton{type='view', name='搜索', key='null', url='http://www.soso.com/', subButtons=[]}, WxMenuButton{type='view', name='视频', key='null', url='http://v.qq.com/', subButtons=[]}, WxMenuButton{type='click', name='赞一下我们', key='V1001_GOOD', url='null', subButtons=[]}]}]}
```

又把创建API的json里``sub_button:[]``去掉，还是成功

```
WxMenu{buttons=[WxMenuButton{type='click', name='今日歌曲', key='V1001_TODAY_MUSIC', url='null', subButtons=[]}, WxMenuButton{type='click', name='歌手简介', key='V1001_TODAY_SINGER', url='null', subButtons=[]}, WxMenuButton{type='null', name='菜单', key='null', url='null', subButtons=[WxMenuButton{type='view', name='搜索', key='null', url='http://www.soso.com/', subButtons=[]}, WxMenuButton{type='view', name='视频', key='null', url='http://v.qq.com/', subButtons=[]}, WxMenuButton{type='click', name='赞一下我们', key='V1001_GOOD', url='null', subButtons=[]}]}]}
```

**从两个结果都可以看出，二级菜单都反序列化成功了**

所以你说

> 现在你反序列化的时候没有二级菜单，所以不会有错

到底是个什么意思？

**Comment by chanjarster** [comment]
我提交了测试代码，没有报错。请阅。

**Comment by jaiiye** [comment]
看来这真是一个奇怪的问题，我又试了下 ，完全使用您给的数据，调用方法fromJson(InputStream is) ，还是不行的！
```
{
    "menu": {
        "button": [
            {
                "type": "click",
                "name": "今日歌曲",
                "key": "V1001_TODAY_MUSIC",
                "sub_button": []
            },
            {
                "type": "click",
                "name": "歌手简介",
                "key": "V1001_TODAY_SINGER",
                "sub_button": []
            },
            {
                "name": "菜单",
                "sub_button": [
                    {
                        "type": "view",
                        "name": "搜索",
                        "url": "http://www.soso.com/",
                        "sub_button": []
                    },
                    {
                        "type": "view",
                        "name": "视频",
                        "url": "http://v.qq.com/",
                        "sub_button": []
                    },
                    {
                        "type": "click",
                        "name": "赞一下我们",
                        "key": "V1001_GOOD",
                        "sub_button": []
                    }
                ]
            }
        ]
    }
}
```
部分异常堆栈如下：
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 34 column 27 path $.menu.button[2].sub_button[2].name
	at com.google.gson.internal.Streams.parse(Streams.java:56) ~[gson-2.3.1.jar:na]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54) ~[gson-2.3.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:810) ~[gson-2.3.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:748) ~[gson-2.3.1.jar:na]
	at me.chanjar.weixin.common.bean.WxMenu.fromJson(WxMenu.java:37) ~[weixin-java-common-1.1.2.jar:na]
	at cn.easypass.weixin.web.mp.controller.WeixinMenuController.createMenu(WeixinMenuController.java:30) ~[WeixinMenuController.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) ~[spring-web-4.0.2.RELEASE.jar:4.0.2.RELEASE]
```

**Comment by chanjarster** [comment]
你的文件编码是不是UTF8？

**Comment by jaiiye** [comment]
我看了下 是utf8无bom格式 我觉得应该不是这个问题吧 是编码问题的话应该开始都报异常了 不会到了$.menu.button[2].sub_button[2].name这块 我改下试试

**Comment by jaiiye** [comment]
使用方法fromJson(String json)，确实没有异常！
数据如下：
```
    private final String menuJson = "{\n"
            + "  \"menu\": {\n"
            + "    \"button\": [\n"
            + "      {\n"
            + "        \"type\": \"click\",\n"
            + "        \"name\": \"今日歌曲\",\n"
            + "        \"key\": \"V1001_TODAY_MUSIC\",\n"
            + "        \"sub_button\": []\n"
            + "      },\n"
            + "      {\n"
            + "        \"type\": \"click\",\n"
            + "        \"name\": \"歌手简介\",\n"
            + "        \"key\": \"V1001_TODAY_SINGER\",\n"
            + "        \"sub_button\": []\n"
            + "      },\n"
            + "      {\n"
            + "        \"name\": \"菜单\",\n"
            + "        \"sub_button\": [\n"
            + "          {\n"
            + "            \"type\": \"view\",\n"
            + "            \"name\": \"搜索\",\n"
            + "            \"url\": \"http://www.soso.com/\",\n"
            + "            \"sub_button\": []\n"
            + "          },\n"
            + "          {\n"
            + "            \"type\": \"view\",\n"
            + "            \"name\": \"视频\",\n"
            + "            \"url\": \"http://v.qq.com/\",\n"
            + "            \"sub_button\": []\n"
            + "          },\n"
            + "          {\n"
            + "            \"type\": \"click\",\n"
            + "            \"name\": \"赞一下我们\",\n"
            + "            \"key\": \"V1001_GOOD\",\n"
            + "            \"sub_button\": []\n"
            + "          }\n"
            + "        ]\n"
            + "      }\n"
            + "    ]\n"
            + "  }\n"
            + "}";
```

**Comment by chanjarster** [comment]
把文件发上来瞅瞅

**Comment by jaiiye** [comment]
这是核心代码：
```
InputStream inputStream = getClass().getResourceAsStream("/menus.json");
WxMenu wxMenu = WxMenu.fromJson(inputStream);
wxMpService.menuCreate(wxMenu);
```
文件不支持啊，没办法发送，格式肯定没问题，见图片。
![20150320161838](https://cloud.githubusercontent.com/assets/463148/6748116/0f6f95c8-cf1d-11e4-940b-2be45a9833c2.jpg)

**Comment by chanjarster** [comment]
如果不要 无BOM 呢

**Comment by jaiiye** [comment]
嗯，我也在弄，好像Netbeans IDE 里面utf8都是无BOM的，直接在外面改成utf8有点问题。

**Comment by jaiiye** [comment]
算了，可能真是编码问题吧，不用流那个方法了，把流手工转成utf-8字符串后再用，没有问题，安全。
```
String menuJson = CharStreams.toString(new InputStreamReader(getClass().getResourceAsStream("/menus.json"), Charset.forName("utf-8")));
```

**Comment by chanjarster** [comment]
你修改下WxMenu，改成这样试试

```java
  public static WxMenu fromJson(InputStream is) {
    return WxGsonBuilder.create().fromJson(new InputStreamReader(is, "UTF-8"), WxMenu.class);
  }
```

**Comment by jaiiye** [comment]
嗯，我没改WxMenu，这边把InputStreamReader里面的Charset.forName("utf-8")参数去掉，就不行了！打印了下字串，确实是乱的。

**Comment by chanjarster** [comment]
我知道了，fromJson(InputStream)里面要设定一下UTF8编码，我的电脑是Mac的所以JDK默认选择UTF8编码
