### ISSUE TITLE
关于demo测试的help?

### ISSUE THREAD

**Issue by smalljason** [chanjarster/weixin-java-tools#140]
斑竹：
做mp的demo实验时，使用的是xstream-1.4.7.jar和xpp3-1.1.4c.jar，但是xpp3能下载版本都试过了，一直报错。请问xstream需要哪个版本的jar包才能跑起来？
Exception in thread "main" com.thoughtworks.xstream.converters.ConversionException: For input string: "可以不填写" : For input string: "可以不填写"
---- Debugging information ----
message             : For input string: "可以不填写"
cause-exception     : java.lang.NumberFormatException
cause-message       : For input string: "可以不填写"
class               : java.lang.Long
required-type       : java.lang.Long
converter-type      : com.thoughtworks.xstream.converters.SingleValueConverterWrapper
wrapped-converter   : com.thoughtworks.xstream.converters.basic.LongConverter
line number         : 7
class[1]            : me.chanjar.weixin.mp.demo.WxMpDemoInMemoryConfigStorage
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
version             : 1.4.7
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1049)
	at me.chanjar.weixin.mp.demo.WxMpDemoInMemoryConfigStorage.fromXml(WxMpDemoInMemoryConfigStorage.java:26)
	at me.chanjar.weixin.mp.demo.WxMpDemoServer.initWeixin(WxMpDemoServer.java:39)
	at me.chanjar.weixin.mp.demo.WxMpDemoServer.main(WxMpDemoServer.java:19)
Caused by: java.lang.NumberFormatException: For input string: "可以不填写"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at java.lang.Long.valueOf(Unknown Source)
	at java.lang.Long.decode(Unknown Source)
	at com.thoughtworks.xstream.converters.basic.LongConverter.fromString(LongConverter.java:31)
	at com.thoughtworks.xstream.converters.SingleValueConverterWrapper.fromString(SingleValueConverterWrapper.java:41)
	at com.thoughtworks.xstream.converters.SingleValueConverterWrapper.unmarshal(SingleValueConverterWrapper.java:49)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 15 more

**Comment by smalljason** [comment]
问题已经解决，config.xml配置文件的错误导致。后期能明白了，其实日志打的很清楚，两个字段数据类型有误。
