### ISSUE TITLE
在调用wxService.userInfo(id, lang)的时候，代码运行一段时间报HttpResponseException: FastReject

### ISSUE THREAD

**Issue by Dearest** [chanjarster/weixin-java-tools#147]
异常
```
Exception in thread "main" java.lang.RuntimeException: org.apache.http.client.HttpResponseException: FastReject
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:565)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:517)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.userInfo(WxMpServiceImpl.java:297)
	at com.ailk.ecp.test.FollowersUtil.getUserList(FollowersUtil.java:69)
	at com.ailk.ecp.test.FollowersUtil.main(FollowersUtil.java:89)
Caused by: org.apache.http.client.HttpResponseException: FastReject
	at me.chanjar.weixin.common.util.http.Utf8ResponseHandler.handleResponse(Utf8ResponseHandler.java:27)
	at me.chanjar.weixin.common.util.http.Utf8ResponseHandler.handleResponse(Utf8ResponseHandler.java:18)
	at me.chanjar.weixin.common.util.http.SimpleGetRequestExecutor.execute(SimpleGetRequestExecutor.java:37)
	at me.chanjar.weixin.common.util.http.SimpleGetRequestExecutor.execute(SimpleGetRequestExecutor.java:20)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:547)
	... 4 more
```
代码：
```java
logger.debug("获取用户详细信息开始");
		List<WxMpUser> users = new ArrayList<WxMpUser>();
		String lang = "zh_CN"; //语言
		for (String id : openIds) {
			WxMpUser user = new WxMpUser();
			 try {
				
				user = wxService.userInfo(id, lang);
				System.out.println(id+" -- "+user.getNickname());
				followdao.insert(user);
			} catch (WxErrorException e) {
				logger.error("获取用户详细信息出错");
				e.printStackTrace();
			}
		}
		logger.debug("获取用户详细信息结束");
```

**Comment by ukid** [comment]
API调太快，疼讯给你拒绝了吧

**Comment by geffzhang** [comment]
这是过载保护

**Comment by huangzf20** [comment]
微信现在可以批量获取用户信息了，一次100个
