### ISSUE TITLE
线上经常出现invalid code错误

### ISSUE THREAD

**Issue by simlegate** [chanjarster/weixin-java-tools#157]
我用的是 `weixin-java-mp 1.1.1`版本

线上运行的时候经常会出现`invalid code`

过一会儿就好了，在过一会儿又出现了。

@chanjarster 能否瞧瞧

**Comment by chanjarster** [comment]
invalid code是啥？异常堆栈是啥？

**Comment by simlegate** [comment]
@chanjarster 
```java

json:{"errcode":40029,"errmsg":"invalid code"} me.chanjar.weixin.common.exception.WxErrorException: 微信错误 errcode=40029, errmsg=invalid code
json:{"errcode":40029,"errmsg":"invalid code"}
        at me.chanjar.weixin.common.util.http.SimpleGetRequestExecutor.execute(SimpleGetRequestExecutor.java:40) ~[weixin-java-common-1.1.1.jar!/:?]
        at me.chanjar.weixin.common.util.http.SimpleGetRequestExecutor.execute(SimpleGetRequestExecutor.java:20) ~[weixin-java-common-1.1.1.jar!/:?]
        at me.chanjar.weixin.mp.api.WxMpServiceImpl.oauth2getAccessToken(WxMpServiceImpl.java:397) ~[weixin-java-mp-1.1.1.jar!/:?]
        at com.haodaibao.wechat.service.impl.WxOauth2Service.getAccessTokenByCode(WxOauth2Service.java:43) ~[wechat-server-1.0.0-SNAPSHOT.jar!/:?]
        at com.haodaibao.wechat.service.impl.WxOauth2Service.getBaseUserInfoByCode(WxOauth2Service.java:83) ~[wechat-server-1.0.0-SNAPSHOT.jar!/:?]
        at com.haodaibao.wechat.service.impl.WxOauth2Service.authByCodeAndType(WxOauth2Service.java:32) ~[wechat-server-1.0.0-SNAPSHOT.jar!/:?]
        at com.haodaibao.wechat.controller.WxOauthController.advanced(WxOauthController.java:36) ~[wechat-server-1.0.0-SNAPSHOT.jar!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_67]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_67]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_67]
        at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) ~[spring-web-4.1.2.RELEASE.jar!/:4.1.2.RELEASE]
```

**Comment by chanjarster** [comment]
根据微信开发文档，这个错误代码的意思是不合法的oauth_code

可能是因为使用oauth2用户授权时，获得的auth_code已经过期了
或者你用同一个code调用了两次 oauth2getAccessToken 方法


> 在 2015年6月18日，15:18，都是牛奶装什么特仑苏丶 <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> 40029

**Comment by simlegate** [comment]
@chanjarster 谢谢解答。

**Comment by developer1981** [comment]
我也发现这个问题， 我的调用逻辑没有同一个code调用两次oauth2getAccessToken，为什么会这样？

**Comment by chanjarster** [comment]
你可以给这段代码添加日志来排查一下

**Comment by developer1981** [comment]
我添加日志了，发现code就是以前用过的， 大概是20分钟前用过的。

**Comment by simlegate** [comment]
大家说有没有可能是微信给的code是重复的。

**Comment by developer1981** [comment]
我觉得就是微信的问题，给了2次相同的code ,不知道原因。

**Comment by opendever** [comment]
我也碰到了这种情况，微信会回掉两次redirect_uri，带的code是一样的。
诡异的是这个问题只出现在android上，同一时间用iphone测试没有问题。
版本weixin-java-mp 1.1.5。

**Comment by chanjarster** [comment]
要不和微信开发团队联系一下？

**Comment by terryl** [comment]
如果微信回调的时候在一段时间没返回，好像是3秒还是5秒，他会重新调用一次，需要根据code做一个过滤，如果处理过了就忽略掉
2015年6月27日 PM4:48于 "都是牛奶装什么特仑苏丶" <notifications@github.com>写道：

**Comment by opendever** [comment]
我是测试环境挂代理测试的，等线上环境再测试下看看。
@terryl  说的差不多

**Comment by fantasyczl** [comment]
我也发现了这个问题，而且我发现出现问题的，都是有android 4.4，而且三星比较多，神马情况？大家有什么好的方案没有？

**Comment by linfan-** [comment]
我也遇到了这种问题，查了下日志，发现第二次使用相同code的请求都来自同一个IP，感觉是微信那边的重复请求。不知道大家这个问题解决了没有？

**Comment by keymao** [comment]
.... 这个问题确实是安卓端最容易出现。 我用ipad调试，非常正常。换成手机，接着40029。  一会儿好，一会儿差。 可能真如上面所说  相同的code请求了两次userInfo. 应该是安卓的缓存机制？  总之，目前只能说是加个判断去重新获取code，不知道作者 汝的新版本是否加入了这个判断？

**Comment by keymao** [comment]
另外 使用花生壳   客户端为安卓的话  会频繁出现...  代理的话  就是这点比较麻烦。

**Comment by geekpeng** [comment]
几天前还是偶尔出现, 现在除了之前已经授权了的用户不会出现,其他的用户都会出现
