### ISSUE TITLE
maven install 走测试用例的时候总会报这个错

### ISSUE THREAD

**Issue by burgleaf** [chanjarster/weixin-java-tools#161]
weixin-java-common 走TestSuite的时候总会报这个错，我想把jar包打到本地都打不了 

testAesEncrypt(me.chanjar.weixin.common.util.crypto.WxCryptUtilTest)  Time elapsed: 0.151 sec  <<< FAILURE!
java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1024)
	at javax.crypto.Cipher.implInit(Cipher.java:790)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:849)
	at javax.crypto.Cipher.init(Cipher.java:1348)
	at javax.crypto.Cipher.init(Cipher.java:1282)
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.encrypt(WxCryptUtil.java:129)
	at me.chanjar.weixin.common.util.crypto.WxCryptUtilTest.testAesEncrypt(WxCryptUtilTest.java:63)

**Comment by chanjarster** [comment]
wiki里有关于加密解密错误的解决办法。
