### ISSUE TITLE
出了这个错以后就不能上传图片了

### ISSUE THREAD

**Issue by gejo** [chanjarster/weixin-java-tools#165]
2015/07/08 16:51:33 - java.lang.ArrayIndexOutOfBoundsException:0:java.lang.ArrayIndexOutOfBoundsException: 0
	at me.chanjar.weixin.common.util.http.MediaDownloadRequestExecutor.getFileName(MediaDownloadRequestExecutor.java:69)
	at me.chanjar.weixin.common.util.http.MediaDownloadRequestExecutor.execute(MediaDownloadRequestExecutor.java:57)
	at me.chanjar.weixin.common.util.http.MediaDownloadRequestExecutor.execute(MediaDownloadRequestExecutor.java:27)
	at me.chanjar.weixin.cp.api.WxCpServiceImpl.executeInternal(WxCpServiceImpl.java:471)
	at me.chanjar.weixin.cp.api.WxCpServiceImpl.execute(WxCpServiceImpl.java:441)
	at me.chanjar.weixin.cp.api.WxCpServiceImpl.mediaDownload(WxCpServiceImpl.java:165)

**Comment by gejo** [comment]
在代码里故意抛这个错可以稳定重现

**Comment by crucify** [comment]
在 FileUtils.createTmpFile 调用之前产生任何exception会导致stream无法关闭，从而当前request无法结束，导致所有后继使用httpClient的地方全部卡住。而httpClient是service全局共享的，一旦block所有消息都发不出去了。粗糙的修改方法如下

    InputStream inputStream = null;
    try{
	    inputStream = InputStreamResponseHandler.INSTANCE.handleResponse(response);
	    
	    // 视频文件不支持下载
	    String fileName = getFileName(response);
	    if (StringUtils.isBlank(fileName)) {
	      return null;
	    }
	    String[] name_ext = fileName.split("\\.");
	    File localFile = FileUtils.createTmpFile(inputStream, name_ext[0], name_ext[1], tmpDirFile);
	    return localFile;
    } finally {
    	if (inputStream != null) {
            inputStream.close();
        }
    }

**Comment by chanjarster** [comment]
感谢，我瞅瞅。

**Comment by crucify** [comment]
直接原因是getFileName从request head里取文件名的时候出错抛异常，这个不知道是微信服务器返回出问题还是代理问题还是什么，总之返回的request头格式不对没有Content-disposition，这个问题没能重现。 但一旦出现，因为没close stream，httpClient的后继请求就全被block了，除非重启application
