### ISSUE TITLE
XStream 类型报错

### ISSUE THREAD

**Issue by marksnoopy** [chanjarster/weixin-java-tools#179]
```java
java.lang.NoSuchMethodError: com.thoughtworks.xstream.XStream.ignoreUnknownElements()V
	at me.chanjar.weixin.common.util.xml.XStreamInitializer.getInstance(XStreamInitializer.java:43)
	at me.chanjar.weixin.mp.util.xml.XStreamTransformer.config_WxMpXmlMessage(XStreamTransformer.java:58)
	at me.chanjar.weixin.mp.util.xml.XStreamTransformer.configXStreamInstance(XStreamTransformer.java:47)
	at me.chanjar.weixin.mp.util.xml.XStreamTransformer.<clinit>(XStreamTransformer.java:13)
	at me.chanjar.weixin.mp.bean.WxMpXmlMessage.fromXml(WxMpXmlMessage.java:382)
```

**Comment by chanjarster** [comment]
你的runtime里可能有老版本的xstream

**Comment by marksnoopy** [comment]
感谢。
