### ISSUE TITLE
1.1.7 to 1.2.0

### ISSUE THREAD

**Issue by zhuyanxuan** [chanjarster/weixin-java-tools#191]
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [loan.service.impl.MySessionManager] for bean with name 'mySessionManager' defined in class path resource [spring-mvc.xml]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: me/chanjar/weixin/common/session/StandardSessionManager : Unsupported major.minor version 51.0 (unable to load class me.chanjar.weixin.common.session.StandardSessionManager) (unable to load class loan.service.impl.MySessionManager)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1265)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:576)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1331)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:316)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:187)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:856)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:813)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:730)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:438)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:416)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:550)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:155)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:92)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:303)
	... 43 more
Caused by: java.lang.UnsupportedClassVersionError: me/chanjar/weixin/common/session/StandardSessionManager : Unsupported major.minor version 51.0 (unable to load class me.chanjar.weixin.common.session.StandardSessionManager) (unable to load class loan.service.impl.MySessionManager)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2858)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1159)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1647)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:258)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:417)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1283)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1254)
	... 57 more

**Comment by zhuyanxuan** [comment]
MySessionManager extends StandardSessionManager

**Comment by chanjarster** [comment]
我用jdk1.7编译的

**Comment by zhuyanxuan** [comment]
我项目用的jdk1.6

**Comment by zhuyanxuan** [comment]
能不能用1.6编译下 pom的公共资源

**Comment by chanjarster** [comment]
你可以fork一个，然后自己编译一下。

**Comment by lamb** [comment]
@chanjarster  能麻烦以后往maven中央库提交的是1.6编译的吗
