### ISSUE TITLE
偶尔会出现以下异常

### ISSUE THREAD

**Issue by chengshou168** [chanjarster/weixin-java-tools#197]
2015-08-18 09:49:31 TaskUtils$LoggingErrorHandler [ERROR] Unexpected error occurred in scheduled task.
java.lang.StackOverflowError
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
	at sun.security.ssl.InputRecord.read(InputRecord.java:480)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:891)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.BHttpConnectionBase.fillInputBuffer(BHttpConnectionBase.java:344)
	at org.apache.http.impl.BHttpConnectionBase.isStale(BHttpConnectionBase.java:364)
	at org.apache.http.impl.conn.CPool.validate(CPool.java:69)
	at org.apache.http.impl.conn.CPool.validate(CPool.java:43)
	at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:247)
	at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:64)
	at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:192)
	at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:185)
	at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:107)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:276)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at me.chanjar.weixin.common.util.http.SimplePostRequestExecutor.execute(SimplePostRequestExecutor.java:43)
	at me.chanjar.weixin.common.util.http.SimplePostRequestExecutor.execute(SimplePostRequestExecutor.java:28)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:567)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:537)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:578)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:537)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:578)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:537)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:578)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:537)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:578)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:537)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:578)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:537)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:578)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:537)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:578)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:537)

**Comment by chanjarster** [comment]
试试新版本，之前好像是解决了一个递归调用导致stackoverflow的错误
