### ISSUE TITLE
发送模版消息后报错。

### ISSUE THREAD

**Issue by lonyel** [chanjarster/weixin-java-tools#237]
2015-11-25 14:59:15.318 ERROR [me.chanjar.weixin.mp.api.WxMpMessageRouter$2 : 191] - Error happened when wait task finish
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252) ~[?:1.7.0_17]
	at java.util.concurrent.FutureTask.get(FutureTask.java:111) ~[?:1.7.0_17]
	at me.chanjar.weixin.mp.api.WxMpMessageRouter$2.run(WxMpMessageRouter.java:184) [wxmp-1.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_17]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.7.0_17]
	at java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.7.0_17]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_17]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_17]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_17]
Caused by: java.lang.NullPointerException
	at me.chanjar.weixin.mp.api.WxMpMessageRouterRule.service(WxMpMessageRouterRule.java:258) ~[wxmp-1.0.jar:?]
	at me.chanjar.weixin.mp.api.WxMpMessageRouter$1.run(WxMpMessageRouter.java:166) ~[wxmp-1.0.jar:?]
	... 6 more

**Comment by lonyel** [comment]
for(String uid: users){
				List<WxUser> wxusers = this.commonDao.find(WxUser.class,new String[]{"wxusertype","userid"},
						new Object[]{C_WXUSERTYPE_USER,Integer.valueOf(uid)});
				for(WxUser user: wxusers){
					if(!StringUtils.isEmpty(user.getOpenid())){
						templateMessage.setToUser(user.getOpenid());
						this.wxApiService.templateSend(templateMessage);	
					}
				}
			}
