### ISSUE TITLE
不知为何 SHA1.gen算法抛异常

### ISSUE THREAD

**Issue by pukingli** [chanjarster/weixin-java-tools#278]
[Handler processing failed; nested exception is java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha1Hex(Ljava/lang/String;)Ljava/lang/String;] with root cause
java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha1Hex(Ljava/lang/String;)Ljava/lang/String;
	at me.chanjar.weixin.common.util.crypto.SHA1.gen(SHA1.java:61)
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:164)
	at me.chanjar.weixin.cp.bean.WxCpXmlMessage.fromEncryptedXml(WxCpXmlMessage.java:420)
	at me.chanjar.weixin.cp.bean.WxCpXmlMessage.fromEncryptedXml(WxCpXmlMessage.java:429)

**Comment by chanjarster** [comment]
在你的项目里可能引入了不同版本的 commons-codec包导致的。

**Comment by kareanyi** [comment]
目测那个类被覆盖了
