### ISSUE TITLE
Building WeiXin Java Tools - CP 1.3.3 -运行 tests 前报错（求帮忙解答 ）

### ISSUE THREAD

**Issue by yili361** [chanjarster/weixin-java-tools#282]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Mar 10, 2016 3:23:27 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.io.IOException: Stream closed
com.thoughtworks.xstream.io.StreamException:  : Stream closed
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:69)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1049)
	at me.chanjar.weixin.cp.api.ApiTestModule.fromXml(ApiTestModule.java:28)
	at me.chanjar.weixin.cp.api.ApiTestModule.configure(ApiTestModule.java:16)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at org.testng.internal.ClassImpl.getInstanceFromGuice(ClassImpl.java:134)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:105)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:186)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:120)
	at org.testng.TestRunner.initMethods(TestRunner.java:409)
	at org.testng.TestRunner.init(TestRunner.java:235)
	at org.testng.TestRunner.init(TestRunner.java:205)
	at org.testng.TestRunner.<init>(TestRunner.java:153)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:522)
	at org.testng.SuiteRunner.init(SuiteRunner.java:157)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:111)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1299)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1286)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: Stream closed
	at java.io.PushbackInputStream.ensureOpen(Unknown Source)
	at java.io.PushbackInputStream.read(Unknown Source)
	at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.getHeader(XmlHeaderAwareReader.java:79)
	at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.<init>(XmlHeaderAwareReader.java:61)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
	... 30 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.160 s
[INFO] Finished at: 2016-03-10T15:23:27+08:00
[INFO] Final Memory: 28M/269M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project wexin-cp: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: There was an error in the forked process
[ERROR] com.google.inject.CreationException: Guice creation errors:
[ERROR] 
[ERROR] 1) An exception was caught and reported. Message:  : Stream closed
[ERROR] at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
[ERROR] 
[ERROR] 1 error
[ERROR] at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
[ERROR] at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
[ERROR] at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
[ERROR] at com.google.inject.Guice.createInjector(Guice.java:95)
[ERROR] at com.google.inject.Guice.createInjector(Guice.java:72)
[ERROR] at org.testng.internal.ClassImpl.getInstanceFromGuice(ClassImpl.java:134)
[ERROR] at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:105)
[ERROR] at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:186)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:120)
[ERROR] at org.testng.TestRunner.initMethods(TestRunner.java:409)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:235)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:205)
[ERROR] at org.testng.TestRunner.<init>(TestRunner.java:153)
[ERROR] at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:522)
[ERROR] at org.testng.SuiteRunner.init(SuiteRunner.java:157)
[ERROR] at org.testng.SuiteRunner.<init>(SuiteRunner.java:111)
[ERROR] at org.testng.TestNG.createSuiteRunner(TestNG.java:1299)
[ERROR] at org.testng.TestNG.createSuiteRunners(TestNG.java:1286)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[ERROR] at org.testng.TestNG.run(TestNG.java:1057)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: com.thoughtworks.xstream.io.StreamException:  : Stream closed
[ERROR] at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:69)
[ERROR] at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1049)
[ERROR] at me.chanjar.weixin.cp.api.ApiTestModule.fromXml(ApiTestModule.java:28)
[ERROR] at me.chanjar.weixin.cp.api.ApiTestModule.configure(ApiTestModule.java:16)
[ERROR] at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
[ERROR] at com.google.inject.spi.Elements.getElements(Elements.java:101)
[ERROR] at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
[ERROR] at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
[ERROR] ... 23 more
[ERROR] Caused by: java.io.IOException: Stream closed
[ERROR] at java.io.PushbackInputStream.ensureOpen(Unknown Source)
[ERROR] at java.io.PushbackInputStream.read(Unknown Source)
[ERROR] at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.getHeader(XmlHeaderAwareReader.java:79)
[ERROR] at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.<init>(XmlHeaderAwareReader.java:61)
[ERROR] at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
[ERROR] ... 30 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]

**Comment by chanjarster** [comment]
首先纠正你一点，这个不是在test前报错，而是在test时报错。

把 weixin-java-cp/src/test/resources/test-config.sample.xml 改成 weixin-java-cp/src/test/resources/test-config.xml 并填入正确的配置即可。

看这篇wiki：https://github.com/chanjarster/weixin-java-tools/wiki/MP_如何执行本项目单元测试

**Comment by yili361** [comment]
是的，就像您说的， 我改了文件名称 test-config.xml, 就测试成功了！ 
感谢您的回复！keep in touch! 





在 2016-03-24 09:15:01，"Daniel Qian" <notifications@github.com> 写道：


首先纠正你一点，这个不是在test前报错，而是在test时报错。

把 weixin-java-cp/src/test/resources/test-config.sample.xml 改成 weixin-java-cp/src/test/resources/test-config.xml 并填入正确的配置即可。

看这篇wiki：https://github.com/chanjarster/weixin-java-tools/wiki/MP_如何执行本项目单元测试
