### ISSUE TITLE
在WxCpMessageHandler类的handle方法里执行mybatis操作报错

### ISSUE THREAD

**Issue by c81113418** [chanjarster/weixin-java-tools#299]
[ERROR]-[2016-04-20 10:53:47] -me.chanjar.weixin.cp.api.WxCpMessageRouter$2.run(WxCpMessageRouter.java:191) -Error happened when wait task finish
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at me.chanjar.weixin.cp.api.WxCpMessageRouter$2.run(WxCpMessageRouter.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at net.hitech.projects.enweac.verify.WxRouterData.startData(WxRouterData.java:26)
	at net.hitech.projects.enweac.verify.WxXmlMessageRouter$1.handle(WxXmlMessageRouter.java:44)
	at me.chanjar.weixin.cp.api.WxCpMessageRouterRule.service(WxCpMessageRouterRule.java:267)
	at me.chanjar.weixin.cp.api.WxCpMessageRouter$1.run(WxCpMessageRouter.java:166)
	... 5 more

**Comment by SimonDolph** [comment]
这个应该是你的业务异常吧，检查下`WxRouterData`26行 😄
