### ISSUE TITLE
根据code来取access_token出现了java.security.InvalidAlgorithmParameterException问题

### ISSUE THREAD

**Issue by changsong** [chanjarster/weixin-java-tools#318]
大侠，看看这个问题，目前微信服务器回调取到了code，但是由code取access_token的时候出现问题
`WxMpOAuth2AccessToken wxMpOAuth2AccessToken =wxMpService.oauth2getAccessToken(code);
`

```
2016-07-05 21:16:49,876 INFO [http-bio-8080-exec-2] [huamai 1.0 prod  1467724609594_121868] c.h.l.u.RecordMonitorUtils - /weixin/authcode.do?code=0319lgrN1Y7GAY02NwtN1sfgrN19lgrj&state=&
2016-07-05 21:17:19,994 ERROR [http-bio-8080-exec-3] [huamai 1.0 prod  1467724639908_121727] error_logger - Api#com.huamai.lawyer.controller.WeiXinController#authcode
java.lang.RuntimeException: javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidAlgorithmParameterException
        at me.chanjar.weixin.mp.api.WxMpServiceImpl.oauth2getAccessToken(WxMpServiceImpl.java:581) ~[weixin-java-mp-1.3.3.jar:na]
        at com.huamai.lawyer.core.service.WeiXinService.getUserByCode(WeiXinService.java:131) ~[huamai-core-1.0-SNAPSHOT.jar:na]
        at com.huamai.lawyer.controller.WeiXinController.authcode(WeiXinController.java:123) ~[classes/:na]
        at com.huamai.lawyer.controller.WeiXinController$$FastClassBySpringCGLIB$$40e2bc6.invoke(<generated>) ~[spring-core-4.2.2.RELEASE.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.2.RELEASE.jar:4.2.2.RELEASE]
```

**Comment by zxkane** [comment]
这种错误多半是jre设置引起的。

换成oracle或openjdk的试试
2016年7月5日 21:23，"Song Chang" <notifications@github.com>写道：

**Comment by changsong** [comment]
解决了，我是在阿里云机器上 
查看系统的nss版本 yum info nss.x86_64 如果是3.16以下，升级nss
yum update nss
