### ISSUE TITLE
WxMpServiceImpl.executeInternal 方法阻塞导致服务器宕机的问题

### ISSUE THREAD

**Issue by WesleyWu** [chanjarster/weixin-java-tools#323]
目前方法的签名是这样的：

protected synchronized T executeInternal(RequestExecutor executor, String uri, E data) throws WxErrorException {...}

里边执行了一个超耗时的https的阻塞请求，直到微信官方网站返回了执行结果，才会结束这个方法。

所以，如果有多个线程通知执行 execute （然后 executeInternal），比如通过16个线程同时发送100万个模板消息，早晚都一定会发生一大堆线程阻塞在这个方法的起始处。

我们就遇到了这个情况，用 jstack 查看我们的 jvm 的线程状况，大部分都这样：
"http-nio-8081-exec-188" #1201 daemon prio=5 os_prio=0 tid=0x00007f99f0498000 nid=0x4822 waiting for monitor entry [0x00007f99c6ef4000]
java.lang.Thread.State: BLOCKED (on object monitor)
at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:729)
- waiting to lock <0x00000000c7332ed8> (a me.chanjar.weixin.mp.api.impl.WxMpServiceImpl)
at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:705)

于是，整个jvm的线程数量耗尽，导致tomcat假死，服务器资源消耗基本为0。

所以我的问题如下：
1、这里的这个 synchronized 关键字为什么一定要加？
2、可以去掉不？
3、如果去掉，会导致什么严重问题？

感谢。

**Comment by zxkane** [comment]
同步锁并不是导致tomcat资源耗尽的最终原因。

你现在是把100w个消息短时间发送给服务器，而服务器处理这些请求的速度(对微信服务器的远程请求)远远跟不上请求进来的速度，会导致服务器没有可用的线程。
WxMpServiceImpl.executeInternal函数有无这个同步锁，在你的这个请求量下都是一样的结局。

合理的做法应该是有消费者来消费这100w个消息，并同步用wechat
api发送请求给微信服务器。也就是说，处理不过来的消息在队列中等待，而不是一股脑扔给服务器程序。


Kane

https://vme360.com

2016-08-16 15:56 GMT+08:00 Wesley Wu <notifications@github.com>:

**Comment by WesleyWu** [comment]
感谢@zxkane， 你说的很有道理，假设我们有1000个线程，如果同时发送消息数量超过1000N(N>5)，会有你说的情况。而同步锁会导致只有一个线程在发请求，假设我有1000个线程，只需要发2000条信息，会有500个线程并发开始发信息，但同时只会有一个线程在工作，其余999个都在blocked排队状态。

所以我的想法是先去掉这个方法上的 synchronized ，同时解决多个线程同时发送失败时去重复刷新Token的重入问题。
